service: GitHubActions

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
resources:
  Resources:
    Functions:
        hello:
          Handler: Lambda_function.lambda_handler
          Runtime: python3.8
          Timeout: 300
          MemorySize: 256
          Policies:
              - AmazonS3FullAccess
              - AmazonTextractFullAccess
              - CloudWatchLogsFullAccess
              - AWSLambdaBasicExecutionRole
          Events:
           - http:
              Path: /Hello
              Method: get

        PostFonction:
          Handler: Lambda_function2.lambda_handler2
          Runtime: python3.8
          Timeout: 300
          MemorySize: 256
          Policies:
              - AmazonS3FullAccess
              - AmazonTextractFullAccess
              - CloudWatchLogsFullAccess
              - AWSLambdaBasicExecutionRole
              - AmazonDynamoDBFullAccess
          Events:
           - http:
              Path: /customer
              Method: post
