service: GitHubActions
provider:
  name: aws
  runtime: python3.8
  region: eu-central-1 
  
functions:  
  HelloWorldFunction-GitHub:
      Handler: Lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /Hello
            Method: get

  PostFunction-GitHub:
      Handler: Lambda_function2.lambda_handler2
      Runtime: python3.8
      Timeout: 300
      MemorySize: 256
      Policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /Customer
            Method: post
