service: GitHubActions
provider:
  name: aws
  runtime: python3.8
  region: eu-central-1 
  
functions:
  HelloWorldFunction-GitHub:
      handler: Lambda_function.lambda_handler
      runtime: python3.8
      timeout: 300
      memorySize: 256
      policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      events:
        MyApi:
          type: api
          properties:
            path: /Hello
            method: get

  PostFunction-GitHub:
      handler: Lambda_function2.lambda_handler2
      handler: python3.8
      timeout: 300
      memorySize: 256
      policies:
        - AmazonS3FullAccess
        - AmazonTextractFullAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      events:
        MyApi:
          type: Api
          properties:
            path: /Customer
            method: post
