service: GitHubActions

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
Resources:      
  function:
    function1:
      handler: Lambda_function.lambda_handler
      runtime: python3.8
      timeout: 300
      memorySize: 256
      Policies:
          - AmazonS3FullAccess
          - AmazonTextractFullAccess
          - CloudWatchLogsFullAccess
          - AWSLambdaBasicExecutionRole
      events:
       - http:
          path: /Hello
          method: get

    function2:
      handler: Lambda_function2.lambda_handler2
      runtime: python3.8
      timeout: 300
      memorySize: 256
      policies:
          - AmazonS3FullAccess
          - AmazonTextractFullAccess
          - CloudWatchLogsFullAccess
          - AWSLambdaBasicExecutionRole
          - AmazonDynamoDBFullAccess
      events:
       - http:
          path: /customer
          method: post
